### ISSUE TITLE
hipchat protocol not recognized

### ISSUE THREAD

**Issue by 97-109-107** [dequis/bitlbee#71]
I've followed this wiki page: http://wiki.bitlbee.org/HowtoHipchat

But I get `Unknown protocol` when trying to 
`account add hipchat your@email.com <password>`

Is there a step missing in the wiki page? Do I need to change some settings in `configure` when making bitlbee?

**Comment by dequis** [comment]
`git checkout feat/hip-cat`?

**Comment by 97-109-107** [comment]
Yes I did that

**Comment by dequis** [comment]
...uh, better join irc if you want to debug this (irc.oftc.net #bitlbee)

(My next guess would be that you're trying to compile with libpurple)

**Comment by 97-109-107** [comment]
Obviously my fault - didn't somehow properly clean up after my previously installing _bitlbee-dx-git_ from Arch's aur
